# 20260702
StylesPath = valestyles
MinAlertLevel = suggestion
# Packages = Hugo , mkdocs
Packages = alex
# mkdocs
# Packages = Google, Microsoft, Readability, alex, Hugo , mkdocs

# Vocab = Zomer, Winter

[*.{md}]
BasedOnStyles = Vale # , AwesomeCo

