name: Vale
on: [pull_request]

jobs:
  vale:
    name: Run vale on the book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - uses: errata-ai/vale-action@2.1.1
#      - uses: vale-cli/vale-action@2.1.2
      - uses: vale-cli/vale-action@v2.1.2
        with:
          version: 3.15.1
